import { formatArabicDate, formatHijriArabicDate } from "./date-utils";
import { DocumentRecord, EventRecord, FamilyMember, PersonalData } from "../shared/personal-data";

function escapeHtml(value?: string) {
  return (value ?? "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#039;", '"': "&quot;" }[character] ?? character));
}

function datePair(value?: string) {
  if (!value) return "—";
  return `${escapeHtml(formatArabicDate(value))}<span class="secondary">${escapeHtml(formatHijriArabicDate(value))}</span>`;
}

export function buildPersonalDataPdfHtml(data: PersonalData, documentImages: Record<string, string[]>) {
  const generatedAt = new Intl.DateTimeFormat("ar-SA-u-ca-gregory", { dateStyle: "medium", timeStyle: "short" }).format(new Date());
  const members = data.members.length ? data.members.map((member) => `<tr><td>${escapeHtml(member.name)}</td><td>${escapeHtml(member.relation)}</td><td>${escapeHtml(member.gender ?? "—")}</td><td>${escapeHtml(member.religion ?? "—")}</td><td>${escapeHtml(member.birthPlace ?? "—")}</td><td>${datePair(member.birthDate)}</td><td>${escapeHtml(member.phone ?? member.email ?? "—")}</td></tr>`).join("") : `<tr><td colspan="7" class="empty">لا توجد بيانات عائلية.</td></tr>`;
  const documents = data.documents.length ? data.documents.map((document) => `<section class="document"><div class="document-copy"><h3>${escapeHtml(document.title)}</h3><p><b>النوع:</b> ${escapeHtml(document.type)} · <b>الرقم:</b> ${escapeHtml(document.number ?? "—")}</p><p><b>مكان الإصدار:</b> ${escapeHtml(document.issuePlace ?? "—")}</p><p><b>الإصدار:</b> ${datePair(document.issueDate)} · <b>الانتهاء:</b> ${datePair(document.expiryDate)}</p></div>${documentImages[document.id]?.length ? `<div class="images">${documentImages[document.id].map((image, index) => `<img src="${image}" alt="صورة ${index + 1} لـ${escapeHtml(document.title)}" />`).join("")}</div>` : ""}</section>`).join("") : `<p class="empty">لا توجد وثائق محفوظة.</p>`;
  const events = data.events.length ? data.events.map((event) => `<tr><td>${escapeHtml(event.title)}</td><td>${escapeHtml(event.category)}</td><td>${datePair(event.date)}</td><td>${event.annualReminder ? "سنوي" : event.hijriOccasionId ? "هجري متكرر" : "مرة واحدة"}</td></tr>`).join("") : `<tr><td colspan="4" class="empty">لا توجد أحداث محفوظة.</td></tr>`;
  return `<!DOCTYPE html><html dir="rtl" lang="ar"><head><meta charset="utf-8"/><style>@page{margin:26px}body{font-family:Arial,sans-serif;color:#102A43;direction:rtl;font-size:12px}.hero{background:#0E7490;color:#fff;border-radius:12px;padding:18px;margin-bottom:20px}.hero h1{margin:0;font-size:24px}.hero p{margin:6px 0 0;color:#DDF6FA}h2{color:#0E7490;border-bottom:1px solid #D9E2EC;padding-bottom:6px;margin-top:22px}table{width:100%;border-collapse:collapse}th{background:#E6F6F8;color:#0E7490}th,td{border:1px solid #D9E2EC;padding:7px;text-align:right;vertical-align:top}.secondary{display:block;color:#627D98;font-size:10px;margin-top:2px}.document{border:1px solid #D9E2EC;border-radius:10px;padding:12px;margin:10px 0;break-inside:avoid}.document-copy{flex:1}.document h3{margin:0 0 7px;color:#243B53}.document p{margin:5px 0;line-height:1.5}.images{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.images img{width:145px;max-height:185px;object-fit:contain;border-radius:7px;border:1px solid #E6EEF4}.empty{color:#829AB1;text-align:center;padding:12px}.footer{margin-top:24px;color:#829AB1;font-size:10px;text-align:center}</style></head><body><div class="hero"><h1>تقرير بياناتي</h1><p>ملخص السجلات والوثائق والأحداث — ${escapeHtml(generatedAt)}</p></div><h2>أفراد العائلة</h2><table><thead><tr><th>الاسم</th><th>القرابة</th><th>الجنس</th><th>الديانة</th><th>مكان الولادة</th><th>الميلاد</th><th>التواصل</th></tr></thead><tbody>${members}</tbody></table><h2>الوثائق</h2>${documents}<h2>الأحداث والمناسبات</h2><table><thead><tr><th>العنوان</th><th>النوع</th><th>التاريخ</th><th>التكرار</th></tr></thead><tbody>${events}</tbody></table><p class="footer">تم إنشاء التقرير محليًا من تطبيق «بياناتي».</p></body></html>`;
}

export function buildMemberPdfHtml(member: FamilyMember, documents: DocumentRecord[], events: EventRecord[], documentImages: Record<string, string[]>) {
  const generatedAt = new Intl.DateTimeFormat("ar-SA-u-ca-gregory", { dateStyle: "medium", timeStyle: "short" }).format(new Date());
  const personalRows = [
    ["صلة القرابة", member.relation], ["الجنس", member.gender], ["الحالة الاجتماعية", member.maritalStatus], ["الجنسية", member.nationality], ["الديانة", member.religion], ["تاريخ الميلاد", member.birthDate ? formatArabicDate(member.birthDate) : undefined], ["التاريخ الهجري للميلاد", member.birthDate ? formatHijriArabicDate(member.birthDate) : undefined], ["مكان الولادة", member.birthPlace], ["رقم الهاتف", member.phone], ["البريد الإلكتروني", member.email], ["العنوان", member.address], ["تاريخ الزواج", member.marriageDate ? formatArabicDate(member.marriageDate) : undefined],
  ].filter(([, value]) => Boolean(value)).map(([label, value]) => `<tr><th>${escapeHtml(label)}</th><td>${escapeHtml(value)}</td></tr>`).join("") || `<tr><td colspan="2" class="empty">لا توجد بيانات إضافية محفوظة.</td></tr>`;
  const documentSections = documents.length ? documents.map((document) => `<section class="document"><h3>${escapeHtml(document.title)}</h3><p><b>النوع:</b> ${escapeHtml(document.type)} · <b>الرقم:</b> ${escapeHtml(document.number ?? "—")}</p><p><b>مكان الإصدار:</b> ${escapeHtml(document.issuePlace ?? "—")}</p><p><b>الإصدار:</b> ${datePair(document.issueDate)} · <b>الانتهاء:</b> ${datePair(document.expiryDate)}</p>${documentImages[document.id]?.length ? `<div class="images">${documentImages[document.id].map((image, index) => `<img src="${image}" alt="صورة ${index + 1} لـ${escapeHtml(document.title)}" />`).join("")}</div>` : ""}</section>`).join("") : `<p class="empty">لا توجد وثائق مرتبطة بهذا الفرد.</p>`;
  const eventRows = events.length ? events.map((event) => `<tr><td>${escapeHtml(event.title)}</td><td>${escapeHtml(event.category)}</td><td>${datePair(event.date)}</td><td>${event.hijriOccasionId ? "هجري متكرر" : event.annualReminder ? "سنوي" : "مرة واحدة"}</td></tr>`).join("") : `<tr><td colspan="4" class="empty">لا توجد أحداث مرتبطة بهذا الفرد.</td></tr>`;
  return `<!DOCTYPE html><html dir="rtl" lang="ar"><head><meta charset="utf-8"/><style>@page{margin:26px}body{font-family:Arial,sans-serif;color:#102A43;direction:rtl;font-size:12px}.hero{background:#0E7490;color:#fff;border-radius:12px;padding:18px;margin-bottom:20px}.hero h1{margin:0;font-size:24px}.hero p{margin:6px 0 0;color:#DDF6FA}h2{color:#0E7490;border-bottom:1px solid #D9E2EC;padding-bottom:6px;margin-top:22px}table{width:100%;border-collapse:collapse}th{background:#E6F6F8;color:#0E7490}th,td{border:1px solid #D9E2EC;padding:7px;text-align:right;vertical-align:top}.secondary{display:block;color:#627D98;font-size:10px;margin-top:2px}.document{border:1px solid #D9E2EC;border-radius:10px;padding:12px;margin:10px 0;break-inside:avoid}.document h3{margin:0 0 7px;color:#243B53}.document p{margin:5px 0;line-height:1.5}.images{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.images img{width:145px;max-height:185px;object-fit:contain;border-radius:7px;border:1px solid #E6EEF4}.empty{color:#829AB1;text-align:center;padding:12px}.footer{margin-top:24px;color:#829AB1;font-size:10px;text-align:center}</style></head><body><div class="hero"><h1>ملف ${escapeHtml(member.name)}</h1><p>${escapeHtml(member.relation)} · تم إنشاؤه في ${escapeHtml(generatedAt)}</p></div><h2>البيانات الشخصية وبيانات الاتصال</h2><table><tbody>${personalRows}</tbody></table><h2>الوثائق المرتبطة</h2>${documentSections}<h2>الأحداث والمناسبات المرتبطة</h2><table><thead><tr><th>العنوان</th><th>النوع</th><th>التاريخ</th><th>التكرار</th></tr></thead><tbody>${eventRows}</tbody></table><p class="footer">تم إنشاء التقرير محليًا من تطبيق «بياناتي».</p></body></html>`;
}
